version: '3.1'

services:
  php:
    #image: php:7.4-apache
    build: ./build/php8-apache
    ports:
    - "8092:80"
    volumes:
    - ./src:/var/www/html
    links:
        - es01
        - es02

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: anaya_mage
      MYSQL_PASSWORD: anaya_pass
      MYSQL_DATABASE: magento2
    volumes:
    - $PWD/data/mysql:/var/lib/mysql
    - $PWD/logs/mysql:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: anaya_es01_1
    volumes:
      - $PWD/es01/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: anaya_es02_1
    volumes:
      - $PWD/es02/data:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1